In [3]:
import reservoirflow as rf
import numpy as np

In [4]:
def create_model_example_7_1():
    grid = rf.grids.Cartesian(
        nx=4, ny=1, nz=1, dx=300, dy=350, dz=40, phi=0.27, kx=270, dtype="double"
    )
    fluid = rf.fluids.SinglePhase(mu=0.5, B=1, dtype="double")
    model = rf.models.Model(grid, fluid, dtype="double", verbose=False)
    model.set_well(id=4, q=-600, s=1.5, r=3.5)
    model.set_boundaries({0: ("pressure", 4000), 5: ("rate", 0)})
    return model


def create_model():
    grid = rf.grids.Cartesian(
        nx=3,
        ny=1,
        nz=1,
        dx=300,
        dy=350,
        dz=20,
        phi=0.27,
        kx=1,
        ky=1,
        kz=0.1,
        comp=1 * 10**-6,
        dtype="double",
    )
    fluid = rf.fluids.SinglePhase(
        mu=0.5, B=1, rho=50, comp=1 * 10**-5, dtype="double"
    )
    model = rf.models.Model(
        grid, fluid, pi=6000, dt=5, start_date="10.10.2018", dtype="double"
    )

    n_samples = 1
    cells_id = model.grid.get_cells_id(False, True)[-1].flatten()
    wells = np.random.choice(cells_id, n_samples, False)
    for id in wells:
        model.set_well(id=id, q=-300, pwf=100, s=1.5, r=3.5)

    wells = np.random.choice(cells_id, n_samples, False)
    for id in wells:
        model.set_well(id=id, q=100, s=0, r=3.5)

    return model


model = create_model()
model.run(10, isolver="cgs")

[info] Simulation run started: 10 timesteps.


[step]: 10 - : 100%|██████████| 10/10 [00:00<00:00, 62.68steps/s]

[info] Simulation run of 10 steps finished in 0.17 seconds.
[info] Material Balance Error: 1.454392162258955e-14.


In [22]:
arr = model.grid.get_cells_center(True, False)
print(arr.shape)
print(arr.min(axis=0))
arr

(5, 3)
[150. 175.  10.]


array([[ 150.,  175.,   10.],
       [ 450.,  175.,   10.],
       [ 750.,  175.,   10.],
       [1050.,  175.,   10.],
       [1350.,  175.,   10.]])

In [32]:
np.count_nonzero(np.array([1, 2, 0, 0]) == 0)

2

In [25]:
scaler = rf.scalers.MinMaxScaler((-1, 1)).fit(arr, axis=0)
scaler.transform(arr)

c:\users\abugrzka\projects\openresim\reservoirflow\scalers.py:60: RuntimeWarning: invalid value encountered in true_divide
  self.vmax - self.vmin


array([[-1. ,  nan,  nan],
       [-0.5,  nan,  nan],
       [ 0. ,  nan,  nan],
       [ 0.5,  nan,  nan],
       [ 1. ,  nan,  nan]])

In [7]:
t = np.arange(0, (model.tstep + 1) * model.dt, model.dt)
rf.scalers.MinMaxScaler((0, 1)).fit_transform(t.reshape(-1, 1), axis=0)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [8]:
t

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [9]:
t, x = model.get_domain(False, True)
t, x

(array([[ 0],
        [ 5],
        [10],
        [15],
        [20],
        [25],
        [30],
        [35],
        [40],
        [45],
        [50]]),
 array([[ 150.],
        [ 450.],
        [ 750.],
        [1050.],
        [1350.]]))

In [10]:
rf.scalers.MinMaxScaler((-1, 1)).fit_transform(x, axis=0)

array([[-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ]])

In [11]:
t

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [12]:
rf.scalers.MinMaxScaler((0, 1)).fit_transform(t.flatten(), axis=0)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
model.get_centers(False)

(array([[ 150.],
        [ 450.],
        [ 750.],
        [1050.],
        [1350.]]),
 ['x'])

In [14]:
t

array([[ 0],
       [ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [15]:
np.repeat(t.flatten(), 2)

array([ 0,  0,  5,  5, 10, 10, 15, 15, 20, 20, 25, 25, 30, 30, 35, 35, 40,
       40, 45, 45, 50, 50])

In [16]:
config = {"time": ["MinMax", (0, 1)], "space": ["minMax"]}

In [17]:
model.set_scalers({"time": ["minmax", (-10, 10)], "rate": ["minmax", None]})
model.scalers_dict

{'time': ['MinMax', (-10, 10)],
 'space': ['MinMax', (-1, 1)],
 'pressure': ['MinMax', (-1, 1)],
 'rate': [None, None]}

In [18]:
model.update_scalers(False)
model.pressures_scaler.transform(model.pressures[1])
# model.space_scaler.transform(model.get_centers(False)[0])

array([0.41367714, 0.02714583, 0.37956372, 0.58787536, 0.41367714])

In [19]:
model.get_df(
    scale=True,
    melt=True,
    boundary=False,
    units=True,
    columns=["time", "cells", "wells"],
)

id  Step    x  Time [Scaled]  Q [Scaled]  P [Scaled]
0    1     0 -0.5          -10.0    0.000000    0.413677
1    2     0  0.0          -10.0    0.000000    0.413677
2    3     0  0.5          -10.0    0.000000    0.413677
3    1     1 -0.5           -8.0 -210.261660    0.027146
4    2     1  0.0           -8.0    0.000000    0.379564
5    3     1  0.5           -8.0  100.000000    0.587875
6    1     2 -0.5           -6.0 -187.135552   -0.252582
7    2     2  0.0           -6.0    0.000000    0.332658
8    3     2  0.5           -6.0  100.000000    0.719752
9    1     3 -0.5           -4.0 -170.190252   -0.457548
10   2     3  0.0           -4.0    0.000000    0.283514
11   3     3  0.5           -4.0  100.000000    0.816978
12   1     4 -0.5           -2.0 -157.628510   -0.609491
13   2     4  0.0           -2.0    0.000000    0.236949
14   3     4  0.5           -2.0  100.000000    0.886682
15   1     5 -0.5            0.0 -148.213227   -0.723376
16   2     5  0.0            0.0    0.000000    0.194812
17   3     5  0.5            0.0  100.000000    0.934958
18   1     6 -0.5            2.0 -141.073776   -0.809733
19   2     6  0.0            2.0    0.000000    0.157460
20   3     6  0.5            2.0  100.000000    0.966863
21   1     7 -0.5            4.0 -135.598989   -0.875955
22   2     7  0.0            4.0    0.000000    0.124604
23   3     7  0.5            4.0  100.000000    0.986372
24   1     8 -0.5            6.0 -131.349563   -0.927355
25   2     8  0.0            6.0    0.000000    0.095694
26   3     8  0.5            6.0  100.000000    0.996614
27   1     9 -0.5            8.0 -128.008139   -0.967772
28   2     9  0.0            8.0    0.000000    0.070123
29   3     9  0.5            8.0  100.000000    1.000000
30   1    10 -0.5           10.0 -125.343714   -1.000000
31   2    10  0.0           10.0    0.000000    0.047330
32   3    10  0.5           10.0  100.000000    0.998375