In [1]:
import reservoirflow as rf
import numpy as np
import pandas as pd

In [2]:
rf.__version__

'0.1.0'

In [18]:
df = pd.DataFrame([[1, 2, 3], [1, 2, 3]], columns=["$a^2$", r"$b^2$", "c^^2"])
df

$a^2$  $b^2$  c^^2
0      1      2     3
1      1      2     3

In [ ]:
rf.F

In [3]:
dir(rf.scalers)

['Dummy',
 'MinMax',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_dummy',
 '_minmax',
 '_scaler']

In [4]:
dir(rf.models)

['BlackOil',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_black_oil',
 '_model']

In [5]:
rf._base.UNITS

{'field': {'transmissibility': 'stb/d-psi',
  'error': 'stb/d',
  'pressure': 'psia',
  'time': 'days',
  'rate': 'stb/day',
  'length': 'ft',
  'area': 'ft^2',
  'volume': 'ft^3'},
 'metric': {'transmissibility': 'm^3/D-bar',
  'error': 'm^3/day',
  'pressure': 'kpa',
  'time': 'days',
  'rate': 'm^3/day',
  'length': 'm',
  'area': 'm^2',
  'volume': 'm^3'},
 'lab': {'transmissibility': 'cm^3/sec-atm',
  'error': 'cm^3/sec',
  'pressure': 'atm',
  'time': 'sec',
  'rate': 'cm^3/sec',
  'length': 'cm',
  'area': 'cm^2',
  'volume': 'cm^3'}}

In [6]:
dir(rf.fluids.SinglePhase)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'allow_synonyms',
 'name',
 'report',
 'set_B',
 'set_comp',
 'set_mu',
 'set_props',
 'set_rho',
 'set_units']

In [7]:
dir(rf.grids.RegularCartesian)

['_RegularCartesian__calc_cells_A',
 '_RegularCartesian__calc_cells_V',
 '_RegularCartesian__calc_cells_d',
 '_RegularCartesian__calc_cells_d_',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'allow_synonyms',
 'extract_boundaries',
 'get_D',
 'get_Vt',
 'get_boundaries',
 'get_cell_A',
 'get_cell_Ax',
 'get_cell_Ay',
 'get_cell_Az',
 'get_cell_G',
 'get_cell_V',
 'get_cell_boundaries',
 'get_cell_center',
 'get_cell_coords',
 'get_cell_d',
 'get_cell_dx',
 'get_cell_dy',
 'get_cell_dz',
 'get_cell_icoords',
 'get_cell_id',
 'get_cell_k',
 'get_cell_kx',
 'get_cell_ky',
 'get_cell_kz',
 'get_cell_neighbors',
 'get_cells_A',
 'get_cells_Ax',
 'get_cells_Ay',
 'get_cell

In [8]:
rf.UNITS

{'field': {'transmissibility': 'stb/d-psi',
  'error': 'stb/d',
  'pressure': 'psia',
  'time': 'days',
  'rate': 'stb/day',
  'length': 'ft',
  'area': 'ft^2',
  'volume': 'ft^3'},
 'metric': {'transmissibility': 'm^3/D-bar',
  'error': 'm^3/day',
  'pressure': 'kpa',
  'time': 'days',
  'rate': 'm^3/day',
  'length': 'm',
  'area': 'm^2',
  'volume': 'm^3'},
 'lab': {'transmissibility': 'cm^3/sec-atm',
  'error': 'cm^3/sec',
  'pressure': 'atm',
  'time': 'sec',
  'rate': 'cm^3/sec',
  'length': 'cm',
  'area': 'cm^2',
  'volume': 'cm^3'}}

In [9]:
type(rf.scalers.MinMax((1, 1)))

reservoirflow.scalers._minmax.MinMax

In [10]:
def create_model_example_7_1():
    grid = rf.grids.Cartesian(
        nx=4, ny=1, nz=1, dx=300, dy=350, dz=40, phi=0.27, kx=270, dtype="double"
    )
    fluid = rf.fluids.SinglePhase(mu=0.5, B=1, dtype="double")
    model = rf.models.BlackOil(grid, fluid, dtype="double", verbose=False)
    model.set_well(id=4, q=-600, s=1.5, r=3.5)
    model.set_boundaries({0: ("pressure", 4000), 5: ("rate", 0)})
    return model


def create_model():
    grid = rf.grids.RegularCartesian(
        nx=3,
        ny=1,
        nz=1,
        dx=300,
        dy=350,
        dz=20,
        phi=0.27,
        kx=1,
        ky=1,
        kz=0.1,
        comp=1 * 10**-6,
        dtype="double",
    )
    fluid = rf.fluids.SinglePhase(
        mu=0.5, B=1, rho=50, comp=1 * 10**-5, dtype="double"
    )
    model = rf.models.BlackOil(
        grid, fluid, pi=6000, dt=5, start_date="10.10.2018", dtype="double"
    )

    n_samples = 1
    cells_id = model.grid.get_cells_id(False, True)[-1].flatten()
    wells = np.random.choice(cells_id, n_samples, False)
    for id in wells:
        model.set_well(id=id, q=-300, pwf=100, s=1.5, r=3.5)

    wells = np.random.choice(cells_id, n_samples, False)
    for id in wells:
        model.set_well(id=id, q=100, s=0, r=3.5)

    return model


model = create_model()
model.run(10, isolver="cgs")

[info] Simulation run started: 10 timesteps.


[step]: 10 - : 100%|██████████| 10/10 [00:00<00:00, 428.64steps/s]

[info] Simulation run of 10 steps finished in 0.04 seconds.
[info] Material Balance Error: 2.55351295663786e-15.


In [11]:
model.units

{'transmissibility': 'stb/d-psi',
 'error': 'stb/d',
 'pressure': 'psia',
 'time': 'days',
 'rate': 'stb/day',
 'length': 'ft',
 'area': 'ft^2',
 'volume': 'ft^3'}

In [12]:
arr = model.grid.get_cells_center(True, False)
print(arr.shape)
print(arr.min(axis=0))
arr

(5, 3)
[150. 175.  10.]


array([[ 150.,  175.,   10.],
       [ 450.,  175.,   10.],
       [ 750.,  175.,   10.],
       [1050.,  175.,   10.],
       [1350.,  175.,   10.]])

In [13]:
np.count_nonzero(np.array([1, 2, 0, 0]) == 0)

2

In [14]:
scaler = rf.scalers.MinMax((-1, 1)).fit(arr, axis=0)
scaler.transform(arr)

C:\Users\abugrzka\Projects\reservoirflow\reservoirflow\scalers\_minmax.py:39: RuntimeWarning: invalid value encountered in true_divide
  self.vmax - self.vmin


array([[-1. ,  nan,  nan],
       [-0.5,  nan,  nan],
       [ 0. ,  nan,  nan],
       [ 0.5,  nan,  nan],
       [ 1. ,  nan,  nan]])

In [15]:
t = np.arange(0, (model.tstep + 1) * model.dt, model.dt)
rf.scalers.MinMax((0, 1)).fit_transform(t, axis=0)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
t

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
t, x = model.get_domain(False, True)
t, x

(array([[ 0],
        [ 5],
        [10],
        [15],
        [20],
        [25],
        [30],
        [35],
        [40],
        [45],
        [50]]),
 array([[ 150.],
        [ 450.],
        [ 750.],
        [1050.],
        [1350.]]))

In [18]:
rf.scalers.MinMax((-1, 1)).fit_transform(x, axis=0)

array([[-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ]])

In [19]:
rf.scalers.MinMax((0, 1)).fit_transform(t, axis=0)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [20]:
model.get_centers(False)

(array([[ 150.],
        [ 450.],
        [ 750.],
        [1050.],
        [1350.]]),
 ['x'])

In [21]:
config = {"time": ["MinMax", (0, 1)], "space": ["minMax"]}

In [22]:
model.set_scalers({"time": ["minmax", (-10, 10)], "rate": ["minmax", None]})
model.scalers_dict

{'time': ['MinMax', (-10, 10)],
 'space': ['MinMax', (-1, 1)],
 'pressure': ['MinMax', (-1, 1)],
 'rate': [None, None]}

In [23]:
model.update_scalers(False)
model.pressures_scaler.transform(model.pressures[1])
# model.space_scaler.transform(model.get_centers(False)[0])

array([        nan, -0.9902352 , -0.94898548, -0.69223375,         nan])

In [25]:
model.get_df(
    scale=False,
    melt=False,
    boundary=True,
    units=True,
    columns=["time", "cells", "wells"],
)

Time [days]  Q3 [stb/day]    P1 [psia]    P2 [psia]    P3 [psia]  \
Step                                                                     
0               0           0.0  6000.000000  6000.000000  6000.000000   
1               5         100.0  6011.925704  6062.303776  6375.873375   
2              10         100.0  6040.467778  6161.038838  6698.699092   
3              15         100.0  6086.523245  6281.076599  6982.708718   
4              20         100.0  6149.124145  6413.570824  7237.716446   
5              25         100.0  6226.497680  6553.348798  7470.667792   
6              30         100.0  6316.631425  6697.385844  7686.599855   
7              35         100.0  6417.559620  6843.913325  7889.247033   
8              40         100.0  6527.494818  6991.897053  8081.430960   
9              45         100.0  6644.875962  7140.732303  8265.317421   
10             50         100.0  6768.373112  7290.065469  8442.589958   

      Qw3 [stb/day]   Pwf3 [psia]  
Step                               
0               0.0   6000.000000  
1             100.0   8282.124330  
2             100.0   8604.950047  
3             100.0   8888.959673  
4             100.0   9143.967401  
5             100.0   9376.918747  
6             100.0   9592.850810  
7             100.0   9795.497988  
8             100.0   9987.681915  
9             100.0  10171.568375  
10            100.0  10348.840913