In [1]:
import reservoirflow as rf
import numpy as np
import pandas as pd

In [2]:
rf.__version__

'0.1.0'

In [ ]:
rf.grids.RegularCartesian(nx=, nz)

In [3]:
df = pd.DataFrame([[1, 2, 3], [1, 2, 3]], columns=["$a^2$", r"$b^2$", "c^^2"])
df

$a^2$  $b^2$  c^^2
0      1      2     3
1      1      2     3

In [4]:
dir(rf.scalers)

['Dummy',
 'MinMax',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_dummy',
 '_minmax',
 '_scaler']

In [5]:
dir(rf.models)

['BlackOil',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_black_oil',
 '_model']

In [6]:
rf._base.UNITS

{'field': {'transmissibility': 'stb/(day.psi)',
  'error': 'stb/day',
  'pressure': 'psia',
  'time': 'days',
  'rate': 'stb/day',
  'length': 'ft',
  'area': 'ft^2',
  'volume': 'ft^3'},
 'metric': {'transmissibility': 'm^3/(day.bar)',
  'error': 'm^3/day',
  'pressure': 'kpa',
  'time': 'days',
  'rate': 'm^3/day',
  'length': 'm',
  'area': 'm^2',
  'volume': 'm^3'},
 'lab': {'transmissibility': 'cm^3/(sec.atm)',
  'error': 'cm^3/sec',
  'pressure': 'atm',
  'time': 'sec',
  'rate': 'cm^3/sec',
  'length': 'cm',
  'area': 'cm^2',
  'volume': 'cm^3'}}

In [7]:
dir(rf.fluids.SinglePhase)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'allow_synonyms',
 'name',
 'report',
 'set_B',
 'set_comp',
 'set_mu',
 'set_props',
 'set_rho',
 'set_units']

In [8]:
dir(rf.grids.RegularCartesian)

['_RegularCartesian__calc_cells_A',
 '_RegularCartesian__calc_cells_V',
 '_RegularCartesian__calc_cells_d',
 '_RegularCartesian__calc_cells_d_',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'allow_synonyms',
 'extract_boundaries',
 'get_D',
 'get_Vt',
 'get_boundaries',
 'get_cell_A',
 'get_cell_Ax',
 'get_cell_Ay',
 'get_cell_Az',
 'get_cell_G',
 'get_cell_V',
 'get_cell_boundaries',
 'get_cell_center',
 'get_cell_coords',
 'get_cell_d',
 'get_cell_dx',
 'get_cell_dy',
 'get_cell_dz',
 'get_cell_icoords',
 'get_cell_id',
 'get_cell_k',
 'get_cell_kx',
 'get_cell_ky',
 'get_cell_kz',
 'get_cell_neighbors',
 'get_cells_A',
 'get_cells_Ax',
 'get_cells_Ay',
 'get_cell

In [9]:
rf.UNITS

{'field': {'transmissibility': 'stb/(day.psi)',
  'error': 'stb/day',
  'pressure': 'psia',
  'time': 'days',
  'rate': 'stb/day',
  'length': 'ft',
  'area': 'ft^2',
  'volume': 'ft^3'},
 'metric': {'transmissibility': 'm^3/(day.bar)',
  'error': 'm^3/day',
  'pressure': 'kpa',
  'time': 'days',
  'rate': 'm^3/day',
  'length': 'm',
  'area': 'm^2',
  'volume': 'm^3'},
 'lab': {'transmissibility': 'cm^3/(sec.atm)',
  'error': 'cm^3/sec',
  'pressure': 'atm',
  'time': 'sec',
  'rate': 'cm^3/sec',
  'length': 'cm',
  'area': 'cm^2',
  'volume': 'cm^3'}}

In [10]:
type(rf.scalers.MinMax((1, 1)))

reservoirflow.scalers._minmax.MinMax

In [11]:
def create_model_example_7_1():
    grid = rf.grids.Cartesian(
        nx=4, ny=1, nz=1, dx=300, dy=350, dz=40, phi=0.27, kx=270, dtype="double"
    )
    fluid = rf.fluids.SinglePhase(mu=0.5, B=1, dtype="double")
    model = rf.models.BlackOil(grid, fluid, dtype="double", verbose=False)
    model.set_well(id=4, q=-600, s=1.5, r=3.5)
    model.set_boundaries({0: ("pressure", 4000), 5: ("rate", 0)})
    return model


def create_model():
    grid = rf.grids.RegularCartesian(
        nx=3,
        ny=1,
        nz=1,
        dx=300,
        dy=350,
        dz=20,
        phi=0.27,
        kx=1,
        ky=1,
        kz=0.1,
        comp=1 * 10**-6,
        dtype="double",
    )
    fluid = rf.fluids.SinglePhase(
        mu=0.5, B=1, rho=50, comp=1 * 10**-5, dtype="double"
    )
    model = rf.models.BlackOil(
        grid, fluid, pi=6000, dt=5, start_date="10.10.2018", dtype="double"
    )

    n_samples = 1
    cells_id = model.grid.get_cells_id(False, True)[-1].flatten()
    wells = np.random.choice(cells_id, n_samples, False)
    for id in wells:
        model.set_well(id=id, q=-300, pwf=100, s=1.5, r=3.5)

    wells = np.random.choice(cells_id, n_samples, False)
    for id in wells:
        model.set_well(id=id, q=100, s=0, r=3.5)

    return model


model = create_model()
model.run(10, isolver="cgs")

[info] Simulation run started: 10 timesteps.


[step]: 10 - : 100%|██████████| 10/10 [00:00<00:00, 62.83steps/s]

[info] Simulation run of 10 steps finished in 0.16 seconds.
[info] Material Balance Error: 9.880984919163893e-15.


In [12]:
model.units

{'transmissibility': 'stb/(day.psi)',
 'error': 'stb/day',
 'pressure': 'psia',
 'time': 'days',
 'rate': 'stb/day',
 'length': 'ft',
 'area': 'ft^2',
 'volume': 'ft^3'}

In [13]:
arr = model.grid.get_cells_center(True, False)
print(arr.shape)
print(arr.min(axis=0))
arr

(5, 3)
[150. 175.  10.]


array([[ 150.,  175.,   10.],
       [ 450.,  175.,   10.],
       [ 750.,  175.,   10.],
       [1050.,  175.,   10.],
       [1350.,  175.,   10.]])

In [14]:
np.count_nonzero(np.array([1, 2, 0, 0]) == 0)

2

In [15]:
scaler = rf.scalers.MinMax((-1, 1)).fit(arr, axis=0)
scaler.transform(arr)

C:\Users\abugrzka\Projects\reservoirflow\reservoirflow\scalers\_minmax.py:39: RuntimeWarning: invalid value encountered in true_divide
  self.vmax - self.vmin


array([[-1. ,  nan,  nan],
       [-0.5,  nan,  nan],
       [ 0. ,  nan,  nan],
       [ 0.5,  nan,  nan],
       [ 1. ,  nan,  nan]])

In [16]:
t = np.arange(0, (model.tstep + 1) * model.dt, model.dt)
rf.scalers.MinMax((0, 1)).fit_transform(t, axis=0)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
t

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
t, x = model.get_domain(False, True)
t, x

(array([[ 0],
        [ 5],
        [10],
        [15],
        [20],
        [25],
        [30],
        [35],
        [40],
        [45],
        [50]]),
 array([[ 150.],
        [ 450.],
        [ 750.],
        [1050.],
        [1350.]]))

In [19]:
rf.scalers.MinMax((-1, 1)).fit_transform(x, axis=0)

array([[-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ]])

In [20]:
rf.scalers.MinMax((0, 1)).fit_transform(t, axis=0)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [21]:
model.get_centers(False)

(array([[ 150.],
        [ 450.],
        [ 750.],
        [1050.],
        [1350.]]),
 ['x'])

In [22]:
config = {"time": ["MinMax", (0, 1)], "space": ["minMax"]}

In [23]:
model.set_scalers({"time": ["minmax", (-10, 10)], "rate": ["minmax", None]})
model.scalers_dict

{'time': ['MinMax', (-10, 10)],
 'space': ['MinMax', (-1, 1)],
 'pressure': ['MinMax', (-1, 1)],
 'rate': [None, None]}

In [24]:
model.update_scalers(False)
model.pressures_scaler.transform(model.pressures[1])
# model.space_scaler.transform(model.get_centers(False)[0])

array([       nan, 0.86235936, 0.15077701, 0.56868551,        nan])

In [42]:
model.get_df(
    scale=True,
    melt=True,
    boundary=True,
    units=True,
    drop_nan=False,
    columns=["time", "cells", "wells"],
)

id  Step    x  Time [Scaled]  Q [Scaled]  P [Scaled]
0    0     0 -1.0          -10.0    0.000000         NaN
1    1     0 -0.5          -10.0    0.000000    0.667615
2    2     0  0.0          -10.0    0.000000    0.667615
3    3     0  0.5          -10.0    0.000000    0.667615
4    4     0  1.0          -10.0    0.000000         NaN
5    0     1 -1.0           -8.0    0.000000         NaN
6    1     1 -0.5           -8.0  100.000000    0.862359
7    2     1  0.0           -8.0 -215.922133    0.150777
8    3     1  0.5           -8.0    0.000000    0.568686
9    4     1  1.0           -8.0    0.000000         NaN
10   0     2 -1.0           -6.0    0.000000         NaN
11   1     2 -0.5           -6.0  100.000000    0.958959
12   2     2  0.0           -6.0 -199.743106   -0.167221
13   3     2  0.5           -6.0    0.000000    0.427824
14   4     2  1.0           -6.0    0.000000         NaN
15   0     3 -1.0           -4.0    0.000000         NaN
16   1     3 -0.5           -4.0  100.000000    0.997204
17   2     3  0.0           -4.0 -189.147301   -0.375482
18   3     3  0.5           -4.0    0.000000    0.274061
19   4     3  1.0           -4.0    0.000000         NaN
20   0     4 -1.0           -2.0    0.000000         NaN
21   1     4 -0.5           -2.0  100.000000    1.000000
22   2     4  0.0           -2.0 -181.670449   -0.522439
23   3     4  0.5           -2.0    0.000000    0.121601
24   4     4  1.0           -2.0    0.000000         NaN
25   0     5 -1.0            0.0    0.000000         NaN
26   1     5 -0.5            0.0  100.000000    0.980818
27   2     5  0.0            0.0 -175.971084   -0.634460
28   3     5  0.5            0.0    0.000000   -0.023118
29   4     5  1.0            0.0    0.000000         NaN
30   0     6 -1.0            2.0    0.000000         NaN
31   1     6 -0.5            2.0  100.000000    0.947799
32   2     6  0.0            2.0 -171.317159   -0.725933
33   3     6  0.5            2.0    0.000000   -0.157645
34   4     6  1.0            2.0    0.000000         NaN
35   0     7 -1.0            4.0    0.000000         NaN
36   1     7 -0.5            4.0  100.000000    0.906015
37   2     7  0.0            4.0 -167.307488   -0.804743
38   3     7  0.5            4.0    0.000000   -0.281508
39   4     7  1.0            4.0    0.000000         NaN
40   0     8 -1.0            6.0    0.000000         NaN
41   1     8 -0.5            6.0  100.000000    0.858734
42   2     8  0.0            6.0 -163.720601   -0.875243
43   3     8  0.5            6.0    0.000000   -0.395156
44   4     8  1.0            6.0    0.000000         NaN
45   0     9 -1.0            8.0    0.000000         NaN
46   1     9 -0.5            8.0  100.000000    0.808134
47   2     9  0.0            8.0 -160.432719   -0.939866
48   3     9  0.5            8.0    0.000000   -0.499420
49   4     9  1.0            8.0    0.000000         NaN
50   0    10 -1.0           10.0    0.000000         NaN
51   1    10 -0.5           10.0  100.000000    0.755709
52   2    10  0.0           10.0 -157.373253   -1.000000
53   3    10  0.5           10.0    0.000000   -0.595237
54   4    10  1.0           10.0    0.000000         NaN